# Generated by Django 2.2.1 on 2019-05-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Название воинской части')),
                ('Number', models.IntegerField(blank=True, null=True, verbose_name='Номер воинской части')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsiblePersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Наименование должности ответственного лица')),
                ('ShortName', models.CharField(max_length=200, verbose_name='Краткое наименование должности ответственного лица')),
                ('MilitaryUnitsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MilitaryUnits', verbose_name='Название воинской части')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, verbose_name='Название мероприятия')),
                ('StartDate', models.DateField(verbose_name='Дата начала мероприятия')),
                ('EndDate', models.DateField(verbose_name='Дата окончания мероприятия')),
                ('StartTime', models.TimeField(verbose_name='Время начала мероприятия')),
                ('EndTime', models.TimeField(verbose_name='Время окончания мероприятия')),
                ('ResponsiblePersonsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ResponsiblePersons', verbose_name='Ответственный')),
            ],
        ),
    ]
