# Generated by Django 2.2.1 on 2019-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Основные мероприятия', 'verbose_name_plural': '3. Основные мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='militaryunits',
            options={'verbose_name': 'Воинские части', 'verbose_name_plural': '1. Воинские части'},
        ),
        migrations.AlterModelOptions(
            name='responsiblepersons',
            options={'verbose_name': 'Ответственные исполнители', 'verbose_name_plural': '2. Ответственные исполнители'},
        ),
        migrations.AlterField(
            model_name='events',
            name='EndTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='StartTime',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала мероприятия'),
        ),
    ]
